name: base
channels:
  - pytorch
  - conda-forge
  - soumith
  - defaults
dependencies:
  - _anaconda_depends=2022.05=py38_0
  - _ipyw_jlab_nb_ext_conf=0.1.0=py38_0
  - _tflow_select=2.3.0=eigen
  - absl-py=0.15.0=pyhd3eb1b0_0
  - aiohttp=3.8.1=py38h2bbff1b_1
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - alabaster=0.7.12=pyhd3eb1b0_0
  - alembic=1.7.5=pyhd3eb1b0_1
  - anaconda=custom=py38_1
  - anaconda-client=1.10.0=py38haa95532_0
  - anaconda-navigator=2.2.0=py38haa95532_0
  - anaconda-project=0.10.2=pyhd3eb1b0_0
  - anyio=3.5.0=py38haa95532_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py38h2bbff1b_0
  - arrow=1.2.2=pyhd3eb1b0_0
  - astor=0.8.1=py38haa95532_0
  - astroid=2.6.6=py38haa95532_0
  - astropy=5.1=py38h080aedc_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - astunparse=1.6.3=pyhd8ed1ab_0
  - async-timeout=4.0.1=pyhd3eb1b0_0
  - atomicwrites=1.4.0=py_0
  - attrs=21.4.0=pyhd3eb1b0_0
  - automat=20.2.0=py_0
  - autopep8=1.6.0=pyhd3eb1b0_0
  - babel=2.9.1=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - backports=1.1=pyhd3eb1b0_0
  - backports.functools_lru_cache=1.6.4=pyhd3eb1b0_0
  - backports.tempfile=1.0=pyhd3eb1b0_1
  - backports.weakref=1.0.post1=py_1
  - bcrypt=3.2.0=py38he774522_0
  - beautifulsoup4=4.11.1=py38haa95532_0
  - binaryornot=0.4.4=pyhd3eb1b0_1
  - bitarray=2.5.1=py38h2bbff1b_0
  - bkcharts=0.2=py38haa95532_1
  - black=19.10b0=py_0
  - blas=1.0=mkl
  - bleach=4.1.0=pyhd3eb1b0_0
  - blinker=1.4=py_1
  - blosc=1.21.0=h19a0ad4_0
  - bokeh=2.4.2=py38haa95532_1
  - boto3=1.24.28=py38haa95532_0
  - botocore=1.27.28=py38haa95532_0
  - bottleneck=1.3.5=py38h080aedc_0
  - brotli=1.0.9=ha925a31_2
  - brotlipy=0.7.0=py38h2bbff1b_1003
  - bzip2=1.0.8=he774522_0
  - ca-certificates=2022.6.15=h5b45459_0
  - certifi=2022.6.15=py38haa95532_0
  - cffi=1.15.0=py38h2bbff1b_1
  - cfitsio=3.470=h2bbff1b_7
  - chardet=4.0.0=py38haa95532_1003
  - charls=2.2.0=h6c2663c_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.0.4=py38haa95532_0
  - cliff=3.7.0=pyhd8ed1ab_1
  - cloudpickle=2.0.0=pyhd3eb1b0_0
  - clyent=1.2.2=py38_1
  - cmaes=0.8.2=pyh44b312d_0
  - cmd2=1.5.0=py38haa244fe_0
  - colorama=0.4.5=py38haa95532_0
  - colorcet=3.0.0=py38haa95532_0
  - colorlog=5.0.1=py38haa95532_1
  - comtypes=1.1.10=py38haa95532_1002
  - conda=4.13.0=py38haa244fe_1
  - conda-build=3.21.9=py38haa95532_0
  - conda-content-trust=0.1.1=pyhd3eb1b0_0
  - conda-env=2.6.0=haa95532_1
  - conda-pack=0.6.0=pyhd3eb1b0_0
  - conda-package-handling=1.8.1=py38h8cc25b3_0
  - conda-repo-cli=1.0.4=pyhd3eb1b0_0
  - conda-token=0.3.0=pyhd3eb1b0_0
  - conda-verify=3.4.2=py_1
  - console_shortcut=0.1.1=4
  - constantly=15.1.0=pyh2b92418_0
  - cookiecutter=1.7.3=pyhd3eb1b0_0
  - cryptography=3.4.8=py38h71e12ea_0
  - cssselect=1.1.0=pyhd3eb1b0_0
  - cudatoolkit=10.2.89=h74a9793_1
  - curl=7.82.0=h2bbff1b_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - cython=0.29.30=py38hd77b12b_0
  - cytoolz=0.11.0=py38he774522_0
  - daal4py=2021.5.0=py38h8cb3d55_0
  - dal=2021.5.0=haa95532_796
  - dask=2022.5.0=py38haa95532_0
  - dask-core=2022.5.0=py38haa95532_0
  - dataclasses=0.8=pyh6d0b6a4_7
  - datashader=0.13.0=pyhd3eb1b0_1
  - datashape=0.5.4=py38haa95532_1
  - debugpy=1.5.1=py38hd77b12b_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - diff-match-patch=20200713=pyhd3eb1b0_0
  - distributed=2022.5.0=py38haa95532_0
  - docutils=0.18.1=py38haa95532_3
  - entrypoints=0.4=py38haa95532_0
  - et_xmlfile=1.1.0=py38haa95532_0
  - executing=0.8.3=pyhd3eb1b0_0
  - filelock=3.6.0=pyhd3eb1b0_0
  - flake8=3.9.2=pyhd3eb1b0_0
  - flask=1.1.2=pyhd3eb1b0_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.10.4=hd328e21_0
  - frozenlist=1.2.0=py38h2bbff1b_0
  - fsspec=2022.3.0=py38haa95532_0
  - future=0.18.2=py38_1
  - gast=0.4.0=pyhd3eb1b0_0
  - gensim=4.1.2=py38hd77b12b_0
  - giflib=5.2.1=h62dcd97_0
  - glob2=0.7=pyhd3eb1b0_0
  - google-api-core=2.2.2=pyhd3eb1b0_0
  - google-auth=2.6.0=pyhd3eb1b0_0
  - google-cloud-core=2.2.2=pyhd3eb1b0_0
  - google-cloud-storage=1.43.0=py38haa95532_0
  - google-crc32c=1.1.2=py38h2bbff1b_0
  - google-pasta=0.2.0=pyhd3eb1b0_0
  - google-resumable-media=1.3.1=pyhd3eb1b0_1
  - googleapis-common-protos=1.53.0=py38h2eaa2aa_0
  - gputil=1.4.0=pyh9f0ad1d_0
  - greenlet=1.1.1=py38hd77b12b_0
  - h5py=2.10.0=py38h5e291fa_0
  - hdf5=1.10.4=h7ebc959_0
  - heapdict=1.0.1=pyhd3eb1b0_0
  - holoviews=1.14.8=pyhd3eb1b0_0
  - hvplot=0.7.3=pyhd3eb1b0_1
  - hyperlink=21.0.0=pyhd3eb1b0_0
  - icc_rt=2019.0.0=h0cc432a_1
  - icu=58.2=ha925a31_3
  - idna=3.3=pyhd3eb1b0_0
  - ignite=0.4.3=py_0
  - imagecodecs=2021.8.26=py38ha1f97ea_0
  - imageio=2.9.0=pyhd3eb1b0_0
  - imagesize=1.4.1=py38haa95532_0
  - importlib-metadata=4.11.3=py38haa95532_0
  - importlib_metadata=4.11.3=hd3eb1b0_0
  - importlib_resources=5.2.0=pyhd3eb1b0_1
  - incremental=21.3.0=pyhd3eb1b0_0
  - inflection=0.5.1=py38haa95532_0
  - iniconfig=1.1.1=pyhd3eb1b0_0
  - intake=0.6.5=pyhd3eb1b0_0
  - intel-openmp=2021.4.0=haa95532_3556
  - intervaltree=3.1.0=pyhd3eb1b0_0
  - ipykernel=6.9.1=py38haa95532_0
  - ipython=8.4.0=py38haa95532_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - ipywidgets=7.6.5=pyhd3eb1b0_1
  - isort=5.9.3=pyhd3eb1b0_0
  - itemadapter=0.3.0=pyhd3eb1b0_0
  - itemloaders=1.0.4=pyhd3eb1b0_1
  - itsdangerous=2.0.1=pyhd3eb1b0_0
  - jdcal=1.4.1=pyhd3eb1b0_0
  - jedi=0.18.1=py38haa95532_1
  - jinja2=2.11.3=pyhd3eb1b0_0
  - jinja2-time=0.2.0=pyhd3eb1b0_3
  - jmespath=0.10.0=pyhd3eb1b0_0
  - joblib=1.1.0=pyhd3eb1b0_0
  - jpeg=9e=h2bbff1b_0
  - jq=1.6=haa95532_1
  - json5=0.9.6=pyhd3eb1b0_0
  - jsonschema=4.4.0=py38haa95532_0
  - jupyter=1.0.0=py38_7
  - jupyter_client=6.1.12=pyhd3eb1b0_0
  - jupyter_console=6.4.0=pyhd3eb1b0_0
  - jupyter_core=4.10.0=py38haa95532_0
  - jupyter_server=1.17.1=py38haa95532_0
  - jupyterlab=3.3.2=pyhd3eb1b0_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=2.10.3=pyhd3eb1b0_1
  - jupyterlab_widgets=1.0.0=pyhd3eb1b0_1
  - keras-applications=1.0.8=py_1
  - keras-preprocessing=1.1.2=pyhd3eb1b0_0
  - keyring=23.4.0=py38haa95532_0
  - kiwisolver=1.4.2=py38hd77b12b_0
  - lazy-object-proxy=1.6.0=py38h2bbff1b_0
  - lcms2=2.12=h83e58a3_0
  - lerc=3.0=hd77b12b_0
  - libaec=1.0.4=h33f27b4_1
  - libarchive=3.4.2=h5e25573_0
  - libcrc32c=1.1.1=ha925a31_2
  - libcurl=7.82.0=h86230a5_0
  - libdeflate=1.8=h2bbff1b_5
  - libiconv=1.16=h2bbff1b_2
  - liblief=0.11.5=hd77b12b_1
  - libpng=1.6.37=h2a8f88b_0
  - libprotobuf=3.19.1=h23ce68f_0
  - libsodium=1.0.18=h62dcd97_0
  - libspatialindex=1.9.3=h6c2663c_0
  - libssh2=1.10.0=hcd4344a_0
  - libtiff=4.2.0=hd0e1b90_0
  - libuv=1.40.0=he774522_0
  - libwebp=1.2.2=h2bbff1b_0
  - libxml2=2.9.14=h0ad7f3c_0
  - libxslt=1.1.35=h2bbff1b_0
  - libzopfli=1.0.3=ha925a31_0
  - llvmlite=0.38.0=py38h23ce68f_0
  - locket=1.0.0=py38haa95532_0
  - lxml=4.9.1=py38h1985fb9_0
  - lz4=3.1.3=py38h2bbff1b_0
  - lz4-c=1.9.3=h2bbff1b_1
  - lzo=2.10=he774522_2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - mako=1.1.4=pyh44b312d_0
  - markdown=3.3.4=py38haa95532_0
  - markupsafe=2.0.1=py38h2bbff1b_0
  - matplotlib=3.5.1=py38haa95532_1
  - matplotlib-base=3.5.1=py38hd77b12b_1
  - matplotlib-inline=0.1.2=pyhd3eb1b0_2
  - mccabe=0.6.1=py38_1
  - menuinst=1.4.18=py38h59b6b97_0
  - mistune=0.8.4=py38he774522_1000
  - mkl=2021.4.0=haa95532_640
  - mkl-service=2.4.0=py38h2bbff1b_0
  - mkl_fft=1.3.1=py38h277e83a_0
  - mkl_random=1.2.2=py38hf11a4ad_0
  - mock=4.0.3=pyhd3eb1b0_0
  - mpmath=1.2.1=py38haa95532_0
  - msgpack-python=1.0.3=py38h59b6b97_0
  - msys2-conda-epoch=20160418=1
  - multidict=5.1.0=py38h2bbff1b_2
  - multipledispatch=0.6.0=py38_0
  - munkres=1.1.4=py_0
  - mypy_extensions=0.4.3=py38haa95532_1
  - navigator-updater=0.2.1=py38_1
  - nbclassic=0.3.5=pyhd3eb1b0_0
  - nbclient=0.5.13=py38haa95532_0
  - nbconvert=6.4.4=py38haa95532_0
  - nbformat=5.3.0=py38haa95532_0
  - nest-asyncio=1.5.5=py38haa95532_0
  - networkx=2.8.4=py38haa95532_0
  - ninja=1.10.2=haa95532_5
  - ninja-base=1.10.2=h6d14046_5
  - nltk=3.7=pyhd3eb1b0_0
  - nose=1.3.7=pyhd3eb1b0_1008
  - notebook=6.4.11=py38haa95532_0
  - nptdms=1.1.0=pyh9f0ad1d_0
  - numba=0.55.1=py38hf11a4ad_0
  - numexpr=2.8.3=py38hb80d3ca_0
  - numpy=1.21.5=py38h7a0a035_3
  - numpy-base=1.21.5=py38hca35cd5_3
  - numpydoc=1.4.0=py38haa95532_0
  - oauthlib=3.2.0=pyhd3eb1b0_0
  - olefile=0.46=pyhd3eb1b0_0
  - onnx=1.10.2=py38hd77b12b_0
  - openjpeg=2.4.0=h4fc8c34_0
  - openpyxl=3.0.10=py38h2bbff1b_0
  - openssl=1.1.1q=h2bbff1b_0
  - opt_einsum=3.3.0=pyhd3eb1b0_1
  - optuna=2.10.0=pyhd8ed1ab_0
  - packaging=21.3=pyhd3eb1b0_0
  - pandas=1.4.2=py38hd77b12b_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - panel=0.13.0=py38haa95532_0
  - parallel=20200322=0
  - param=1.12.0=pyhd3eb1b0_0
  - paramiko=2.8.1=pyhd3eb1b0_0
  - parsel=1.6.0=py38haa95532_0
  - parso=0.8.3=pyhd3eb1b0_0
  - partd=1.2.0=pyhd3eb1b0_1
  - pathspec=0.7.0=py_0
  - patsy=0.5.2=py38haa95532_1
  - pbr=5.6.0=pyhd3eb1b0_0
  - pep8=1.7.1=py38haa95532_1
  - perl=5.32.1.1=1_h57928b3_strawberry
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=9.2.0=py38hdc2b20a_1
  - pip=22.1.2=py38haa95532_0
  - pkginfo=1.8.2=pyhd3eb1b0_0
  - plotly=5.6.0=pyhd3eb1b0_0
  - pluggy=1.0.0=py38haa95532_1
  - powershell_shortcut=0.0.1=3
  - poyo=0.5.0=pyhd3eb1b0_0
  - prettytable=2.1.0=pyhd8ed1ab_0
  - prometheus_client=0.13.1=pyhd3eb1b0_0
  - prompt-toolkit=3.0.20=pyhd3eb1b0_0
  - prompt_toolkit=3.0.20=hd3eb1b0_0
  - protego=0.1.16=py_0
  - psutil=5.9.0=py38h2bbff1b_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - py=1.11.0=pyhd3eb1b0_0
  - py-lief=0.11.5=py38hd77b12b_1
  - pyasn1=0.4.8=pyhd3eb1b0_0
  - pycodestyle=2.7.0=pyhd3eb1b0_0
  - pycosat=0.6.3=py38h2bbff1b_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyct=0.4.8=py38_0
  - pycurl=7.45.1=py38hcd4344a_0
  - pydispatcher=2.0.5=py38haa95532_2
  - pydocstyle=6.1.1=pyhd3eb1b0_0
  - pyerfa=2.0.0=py38h2bbff1b_0
  - pyflakes=2.3.1=pyhd3eb1b0_0
  - pygments=2.11.2=pyhd3eb1b0_0
  - pyhamcrest=2.0.2=pyhd3eb1b0_2
  - pyjwt=2.4.0=py38haa95532_0
  - pylint=2.9.6=py38haa95532_1
  - pyls-spyder=0.4.0=pyhd3eb1b0_0
  - pynacl=1.4.0=py38h62dcd97_1
  - pyodbc=4.0.32=py38hd77b12b_1
  - pyopenssl=21.0.0=pyhd3eb1b0_1
  - pyparsing=3.0.4=pyhd3eb1b0_0
  - pyperclip=1.8.1=pyhd3deb0d_0
  - pyqt=5.9.2=py38hd77b12b_6
  - pyreadline=2.1=py38_1
  - pyreadline3=3.3=py38haa244fe_1
  - pyrsistent=0.18.0=py38h196d8e1_0
  - pysocks=1.7.1=py38haa95532_0
  - pytables=3.6.1=py38ha5be198_0
  - pytest=7.1.2=py38haa95532_0
  - python=3.8.13=h6244533_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-fastjsonschema=2.15.1=pyhd3eb1b0_0
  - python-libarchive-c=2.9=pyhd3eb1b0_1
  - python-lsp-black=1.0.0=pyhd3eb1b0_0
  - python-lsp-jsonrpc=1.0.0=pyhd3eb1b0_0
  - python-lsp-server=1.2.4=pyhd3eb1b0_0
  - python-slugify=5.0.2=pyhd3eb1b0_0
  - python-snappy=0.6.0=py38hd77b12b_3
  - python_abi=3.8=1_cp38
  - pytorch=1.7.1=py3.8_cuda102_cudnn7_0
  - pytz=2022.1=py38haa95532_0
  - pyviz_comms=2.0.2=pyhd3eb1b0_0
  - pywavelets=1.3.0=py38h2bbff1b_0
  - pywin32=302=py38h2bbff1b_2
  - pywin32-ctypes=0.2.0=py38_1000
  - pywinpty=2.0.2=py38h5da7b33_0
  - pyyaml=6.0=py38h2bbff1b_1
  - pyzmq=23.2.0=py38hd77b12b_0
  - qdarkstyle=3.0.2=pyhd3eb1b0_0
  - qstylizer=0.1.10=pyhd3eb1b0_0
  - qt=5.9.7=vc14h73c81de_0
  - qtawesome=1.0.3=pyhd3eb1b0_0
  - qtconsole=5.3.1=py38haa95532_0
  - qtpy=2.0.1=pyhd3eb1b0_0
  - queuelib=1.5.0=py38haa95532_0
  - ray-core=1.6.0=py38hd77b12b_0
  - ray-tune=1.6.0=py38haa95532_0
  - redis-py=3.5.3=pyhd3eb1b0_0
  - regex=2022.3.15=py38h2bbff1b_0
  - requests=2.28.1=py38haa95532_0
  - requests-file=1.5.1=pyhd3eb1b0_0
  - requests-oauthlib=1.3.0=pyh9f0ad1d_0
  - rope=0.22.0=pyhd3eb1b0_0
  - rtree=0.9.7=py38h2eaa2aa_1
  - ruamel_yaml=0.15.100=py38h2bbff1b_0
  - s3transfer=0.6.0=py38haa95532_0
  - scikit-image=0.19.2=py38hf11a4ad_0
  - scikit-learn=1.0.2=py38hf11a4ad_1
  - scikit-learn-intelex=2021.5.0=py38haa95532_0
  - scipy=1.7.3=py38h0a974cb_0
  - scrapy=2.6.1=py38haa95532_0
  - seaborn=0.11.2=pyhd3eb1b0_0
  - send2trash=1.8.0=pyhd3eb1b0_1
  - service_identity=18.1.0=pyhd3eb1b0_1
  - setproctitle=1.1.10=py38he774522_1001
  - setuptools=61.2.0=py38haa95532_0
  - sip=4.19.13=py38hd77b12b_0
  - six=1.16.0=pyhd3eb1b0_1
  - smart_open=5.2.1=py38haa95532_0
  - snappy=1.1.9=h6c2663c_0
  - sniffio=1.2.0=py38haa95532_1
  - snowballstemmer=2.2.0=pyhd3eb1b0_0
  - sortedcollections=2.1.0=pyhd3eb1b0_0
  - sortedcontainers=2.4.0=pyhd3eb1b0_0
  - soupsieve=2.3.1=pyhd3eb1b0_0
  - sphinx=5.0.2=py38haa95532_0
  - sphinxcontrib-applehelp=1.0.2=pyhd3eb1b0_0
  - sphinxcontrib-devhelp=1.0.2=pyhd3eb1b0_0
  - sphinxcontrib-htmlhelp=2.0.0=pyhd3eb1b0_0
  - sphinxcontrib-jsmath=1.0.1=pyhd3eb1b0_0
  - sphinxcontrib-qthelp=1.0.3=pyhd3eb1b0_0
  - sphinxcontrib-serializinghtml=1.1.5=pyhd3eb1b0_0
  - spyder=5.1.5=py38haa95532_1
  - spyder-kernels=2.1.1=py38haa95532_0
  - sqlalchemy=1.4.39=py38h2bbff1b_0
  - sqlite=3.38.5=h2bbff1b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - statsmodels=0.13.2=py38h2bbff1b_0
  - stevedore=3.3.0=py38haa244fe_1
  - sympy=1.10.1=py38haa95532_0
  - tabulate=0.8.10=py38haa95532_0
  - tbb=2021.5.0=h59b6b97_0
  - tbb4py=2021.5.0=py38h59b6b97_0
  - tblib=1.7.0=pyhd3eb1b0_0
  - tenacity=8.0.1=py38haa95532_1
  - tensorboard=2.6.0=py_1
  - tensorboard-data-server=0.6.0=py38haa95532_0
  - tensorboard-plugin-wit=1.8.0=pyh44b312d_0
  - tensorboardx=2.2=pyhd3eb1b0_0
  - tensorflow=2.3.0=mkl_py38h8c0d9a2_0
  - tensorflow-base=2.3.0=eigen_py38h75a453f_0
  - tensorflow-estimator=2.6.0=pyh7b7c402_0
  - termcolor=1.1.0=py_2
  - terminado=0.13.1=py38haa95532_0
  - testpath=0.6.0=py38haa95532_0
  - text-unidecode=1.3=pyhd3eb1b0_0
  - textdistance=4.2.1=pyhd3eb1b0_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - three-merge=0.1.1=pyhd3eb1b0_0
  - tifffile=2021.7.2=pyhd3eb1b0_2
  - tinycss=0.4=pyhd3eb1b0_1002
  - tk=8.6.12=h2bbff1b_0
  - tldextract=3.2.0=pyhd3eb1b0_0
  - toml=0.10.2=pyhd3eb1b0_0
  - tomli=2.0.1=py38haa95532_0
  - toolz=0.11.2=pyhd3eb1b0_0
  - torchaudio=0.7.2=py38
  - torchvision=0.2.1=py_2
  - tornado=6.1=py38h2bbff1b_0
  - tqdm=4.64.0=py38haa95532_0
  - traitlets=5.1.1=pyhd3eb1b0_0
  - twisted=22.2.0=py38h2bbff1b_0
  - twisted-iocpsupport=1.0.2=py38h2bbff1b_0
  - typed-ast=1.4.3=py38h2bbff1b_1
  - typing-extensions=4.1.1=hd3eb1b0_0
  - typing_extensions=4.1.1=pyh06a4308_0
  - ujson=5.4.0=py38hd77b12b_0
  - unidecode=1.2.0=pyhd3eb1b0_0
  - urllib3=1.26.9=py38haa95532_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - w3lib=1.21.0=pyhd3eb1b0_0
  - watchdog=2.1.6=py38haa95532_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py38_1
  - websocket-client=0.58.0=py38haa95532_4
  - werkzeug=2.0.3=pyhd3eb1b0_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - widgetsnbextension=3.5.2=py38haa95532_0
  - win_inet_pton=1.1.0=py38haa95532_0
  - win_unicode_console=0.5=py38_0
  - wincertstore=0.2=py38haa95532_2
  - winpty=0.4.3=4
  - wrapt=1.12.1=py38he774522_1
  - xarray=0.20.1=pyhd3eb1b0_1
  - xlrd=2.0.1=pyhd3eb1b0_0
  - xlsxwriter=3.0.3=pyhd3eb1b0_0
  - xlwings=0.24.9=py38haa95532_0
  - xz=5.2.5=h8cc25b3_1
  - yaml=0.2.5=he774522_0
  - yapf=0.31.0=pyhd3eb1b0_0
  - yarl=1.6.3=py38h294d835_1
  - zeromq=4.3.4=hd77b12b_0
  - zfp=0.5.5=hd77b12b_6
  - zict=2.1.0=py38haa95532_0
  - zipp=3.8.0=py38haa95532_0
  - zlib=1.2.12=h8cc25b3_2
  - zope=1.0=py38_1
  - zope.interface=5.4.0=py38h2bbff1b_0
  - zstd=1.4.9=h19a0ad4_0
  - pip:
    - appdirs==1.4.4
    - bunch==1.0.1
    - cachetools==4.2.0
    - google-auth-oauthlib==0.4.2
    - grpcio==1.32.0
    - gym==0.17.3
    - importlib-resources==5.3.0
    - notebook-as-pdf==0.3.1
    - protobuf==3.14.0
    - pyasn1-modules==0.2.8
    - pyee==7.0.4
    - pyglet==1.5.0
    - pypdf2==1.26.0
    - pyppeteer==0.2.2
    - pyqt5==5.15.6
    - pyqt5-qt5==5.15.2
    - pyqt5-sip==12.10.1
    - pyqtwebengine==5.15.5
    - pyqtwebengine-qt5==5.15.2
    - rsa==4.7
    - tensorflow-addons==0.12.1
    - typeguard==2.11.1
    - websockets==8.1
prefix: C:\Users\cpras\anaconda3
